services:
  backend:
    image: ghcr.io/fblettner/liberty-framework:latest
    command: [liberty-start]
    security_opt:
      - "label:disable"
    cap_drop:
      - MKNOD
      - AUDIT_WRITE
    networks:
      - liberty-network
    volumes:
      - liberty-config:/liberty-framework/app/config/files     
      - liberty-logs:/liberty-framework/app/logs/files
      - liberty-versions:/liberty-framework/app/alembic/versions
    working_dir: /
    depends_on:
      - pg
    labels:
      - "traefik.enable=true"

      # HTTP Router for REACT (to support redirection)
      - "traefik.http.routers.react.rule=Host(`liberty.nomana-it.fr`) && PathPrefix(`/`)" 
      - "traefik.http.routers.react.entrypoints=web"
      - "traefik.http.routers.react.middlewares=error-pages-middleware"      
  
      # HTTPS Router for REACT
      - "traefik.http.routers.react-https.rule=Host(`liberty.nomana-it.fr`) && PathPrefix(`/`)" 
      - "traefik.http.routers.react-https.entrypoints=websecure"
      - "traefik.http.routers.react-https.middlewares=error-pages-middleware"   
      - "traefik.http.routers.react-https.tls.certresolver=myresolver"
      
      # Framework Service (Port 8000)
      - "traefik.http.services.framework.loadbalancer.server.port=8000"
      - "traefik.http.routers.react.middlewares=compress-middleware"      
      - "traefik.http.routers.react-https.middlewares=compress-middleware"
      - "traefik.http.routers.framework.middlewares=compress-middleware"      
      - "traefik.http.routers.framework-https.middlewares=compress-middleware"
  pg:
    image: ghcr.io/fblettner/liberty-enterprise-pg:latest
    shm_size: 512mb
    command: |
      postgres
        -c shared_buffers=2GB
        -c track_activity_query_size=1MB
        -c work_mem=256MB
        -c maintenance_work_mem=128MB
        -c max_wal_size=8GB
        -c wal_level=minimal
        -c max_wal_senders=0
        -c synchronous_commit=off
        -c checkpoint_timeout=20min
        -c seq_page_cost=1
        -c random_page_cost=4
        -c cpu_tuple_cost=0.03
        -c cpu_index_tuple_cost=0.005
        -c cpu_operator_cost=0.0025
        -c logging_collector=on
        -c log_destination='stderr'
        -c log_directory='/var/log/postgresql'  
        -c log_rotation_age=1d
        -c log_rotation_size=10MB     
    volumes:
      - pg-data:/var/lib/postgresql/data:Z
      - pg-logs:/var/log/postgresql 
    environment:
      - POSTGRES_USER=liberty
      - POSTGRES_PASSWORD=change_on_install      
    networks:
      - liberty-network       
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.pg.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.pg.entryPoints=db"
      - "traefik.http.services.pg.loadbalancer.server.port=5432"
volumes:
  liberty-config:
    name: liberty-config  
  liberty-logs:
    name: liberty-logs   
  liberty-versions:
    name: liberty-versions     
  pg-data:
    name: pg-data
  pg-logs:
    name: pg-logs    
  pgadmin-data:
    name: pgadmin-data 
networks:
  liberty-network:
    external: true