"""Initial migration

Revision ID: 745de9a9edfd
Revises: 
Create Date: 2025-01-31 19:09:11.333185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745de9a9edfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_liberty() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databasechangeloglock',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('locked', sa.BOOLEAN(), nullable=False),
    sa.Column('lockgranted', sa.TIMESTAMP(), nullable=True),
    sa.Column('lockedby', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ly_actions',
    sa.Column('act_id', sa.INTEGER(), nullable=False),
    sa.Column('act_label', sa.VARCHAR(length=255), nullable=True),
    sa.Column('act_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('act_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('act_id')
    )
    op.create_table('ly_api',
    sa.Column('api_id', sa.INTEGER(), nullable=False),
    sa.Column('api_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('api_source', sa.VARCHAR(length=20), nullable=True),
    sa.Column('api_method', sa.VARCHAR(length=20), nullable=True),
    sa.Column('api_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('api_user', sa.VARCHAR(length=100), nullable=True),
    sa.Column('api_password', sa.TEXT(), nullable=True),
    sa.Column('api_body', sa.TEXT(), nullable=True),
    sa.Column('api_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('api_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('api_id')
    )
    op.create_table('ly_api_header',
    sa.Column('api_id', sa.INTEGER(), nullable=False),
    sa.Column('hdr_id', sa.INTEGER(), nullable=False),
    sa.Column('hdr_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hdr_value', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hdr_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('hdr_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('api_id', 'hdr_id')
    )
    op.create_table('ly_api_params',
    sa.Column('api_id', sa.INTEGER(), nullable=False),
    sa.Column('map_id', sa.INTEGER(), nullable=False),
    sa.Column('map_var', sa.VARCHAR(length=100), nullable=False),
    sa.Column('map_value', sa.VARCHAR(length=100), nullable=False),
    sa.Column('map_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('map_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('api_id', 'map_id')
    )
    op.create_table('ly_applications',
    sa.Column('apps_id', sa.INTEGER(), nullable=False),
    sa.Column('apps_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('apps_description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('apps_version', sa.INTEGER(), nullable=True),
    sa.Column('apps_pool', sa.VARCHAR(length=50), nullable=True),
    sa.Column('apps_pool_min', sa.INTEGER(), nullable=True),
    sa.Column('apps_pool_max', sa.INTEGER(), nullable=True),
    sa.Column('apps_dbtype', sa.VARCHAR(length=10), nullable=True),
    sa.Column('apps_jdbc', sa.VARCHAR(length=500), nullable=True),
    sa.Column('apps_user', sa.VARCHAR(length=20), nullable=True),
    sa.Column('apps_password', sa.TEXT(), nullable=True),
    sa.Column('apps_host', sa.VARCHAR(length=100), nullable=True),
    sa.Column('apps_port', sa.INTEGER(), nullable=True),
    sa.Column('apps_database', sa.VARCHAR(length=100), nullable=True),
    sa.Column('apps_offset', sa.INTEGER(), nullable=True),
    sa.Column('apps_limit', sa.INTEGER(), nullable=True),
    sa.Column('apps_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('apps_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('apps_dashboard', sa.INTEGER(), nullable=True),
    sa.Column('apps_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('apps_theme', sa.VARCHAR(length=20), nullable=True),
    sa.Column('apps_replace_null', sa.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('apps_id')
    )
    op.create_table('ly_charts',
    sa.Column('crt_id', sa.INTEGER(), nullable=False),
    sa.Column('crt_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('crt_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('crt_grid_hz', sa.VARCHAR(length=1), nullable=True),
    sa.Column('crt_grid_vt', sa.VARCHAR(length=1), nullable=True),
    sa.Column('crt_axis_x', sa.VARCHAR(length=50), nullable=True),
    sa.Column('crt_axis_y1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('crt_axis_y2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('crt_query_id', sa.INTEGER(), nullable=True),
    sa.Column('crt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('crt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('crt_id')
    )
    op.create_table('ly_components',
    sa.Column('cpt_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cpt_description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cpt_enabled', sa.VARCHAR(length=1), nullable=True),
    sa.Column('cpt_usage', sa.TEXT(), nullable=True),
    sa.Column('cpt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cpt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('cpt_name')
    )
    op.create_table('ly_condition',
    sa.Column('cdn_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cdn_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cdn_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('cdn_id')
    )
    op.create_table('ly_ctxmenus',
    sa.Column('ctx_id', sa.INTEGER(), nullable=False),
    sa.Column('ctx_description', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ctx_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('ctx_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('ctx_id')
    )
    op.create_table('ly_dashboard',
    sa.Column('dsh_id', sa.INTEGER(), nullable=False),
    sa.Column('dsh_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dsh_row', sa.INTEGER(), nullable=True),
    sa.Column('dsh_column', sa.INTEGER(), nullable=True),
    sa.Column('dsh_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('dsh_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('dsh_id')
    )
    op.create_table('ly_db_schema',
    sa.Column('sch_id', sa.INTEGER(), nullable=False),
    sa.Column('sch_pool', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sch_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('sch_target', sa.VARCHAR(length=30), nullable=True),
    sa.Column('sch_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('sch_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('sch_id')
    )
    op.create_table('ly_dialogs',
    sa.Column('dlg_id', sa.INTEGER(), nullable=False),
    sa.Column('dlg_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dlg_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('dlg_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('dlg_id')
    )
    op.create_table('ly_dictionary',
    sa.Column('dd_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dd_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dd_type', sa.VARCHAR(length=40), nullable=True),
    sa.Column('dd_rules', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dd_rules_values', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dd_default', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dd_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('dd_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('dd_id')
    )
    op.create_table('ly_enum',
    sa.Column('enum_id', sa.INTEGER(), nullable=False),
    sa.Column('enum_label', sa.VARCHAR(length=40), nullable=False),
    sa.Column('enum_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('enum_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('enum_display_add', sa.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('enum_id')
    )
    op.create_table('ly_events',
    sa.Column('evt_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_component', sa.VARCHAR(length=20), nullable=False),
    sa.Column('evt_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('evt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('evt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('evt_id')
    )
    op.create_table('ly_evt_cpt',
    sa.Column('evt_component', sa.VARCHAR(length=20), nullable=False),
    sa.Column('evt_cpt_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_col_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_seq_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_act_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('evt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('evt_component', 'evt_cpt_id', 'evt_id', 'evt_col_id')
    )
    op.create_table('ly_evt_dd',
    sa.Column('evt_component', sa.VARCHAR(length=20), nullable=False),
    sa.Column('evt_cpt_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_dd_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('evt_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_act_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('evt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('evt_component', 'evt_cpt_id', 'evt_dd_id', 'evt_id')
    )
    op.create_table('ly_function',
    sa.Column('fct_id', sa.INTEGER(), nullable=False),
    sa.Column('fct_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fct_label', sa.VARCHAR(length=255), nullable=True),
    sa.Column('fct_script', sa.TEXT(), nullable=True),
    sa.Column('fct_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('fct_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('fct_id')
    )
    op.create_table('ly_language',
    sa.Column('lng_id', sa.VARCHAR(length=5), nullable=False),
    sa.Column('lng_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lng_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lng_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('lng_id')
    )
    op.create_table('ly_links',
    sa.Column('lnk_id', sa.INTEGER(), nullable=False),
    sa.Column('lnk_component', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lnk_component_id', sa.INTEGER(), nullable=True),
    sa.Column('lnk_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lnk_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('lnk_id')
    )
    op.create_table('ly_lookup',
    sa.Column('lkp_id', sa.INTEGER(), nullable=False),
    sa.Column('lkp_description', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lkp_query_id', sa.INTEGER(), nullable=True),
    sa.Column('lkp_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lkp_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('lkp_display_add', sa.VARCHAR(length=1), nullable=True),
    sa.Column('lkp_frm_id', sa.INTEGER(), nullable=True),
    sa.Column('lkp_dd_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lkp_dd_label', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lkp_dd_group', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lkp_display_search', sa.VARCHAR(length=1), nullable=True),
    sa.Column('lkp_tbl_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('lkp_id')
    )
    op.create_table('ly_menus',
    sa.Column('menu_seq_ukid', sa.VARCHAR(length=150), nullable=False),
    sa.Column('menu_parent_id', sa.VARCHAR(length=40), nullable=True),
    sa.Column('menu_child_id', sa.VARCHAR(length=40), nullable=True),
    sa.Column('menu_component', sa.VARCHAR(length=40), nullable=True),
    sa.Column('menu_component_id', sa.INTEGER(), nullable=True),
    sa.Column('menu_label', sa.VARCHAR(length=50), nullable=True),
    sa.Column('menu_level', sa.INTEGER(), nullable=True),
    sa.Column('menu_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('menu_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('menu_seq_ukid')
    )
    op.create_table('ly_modules',
    sa.Column('module_id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('module_description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('module_enabled', sa.VARCHAR(length=1), nullable=True),
    sa.Column('module_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('module_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('module_params', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('ly_nextnum',
    sa.Column('nn_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nn_current', sa.INTEGER(), nullable=True),
    sa.Column('nn_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('nn_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('nn_id')
    )
    op.create_table('ly_qry_fmw',
    sa.Column('fmw_id', sa.INTEGER(), nullable=False),
    sa.Column('fmw_dbtype', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fmw_crud', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fmw_description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fmw_pool', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fmw_sqlquery', sa.TEXT(), nullable=True),
    sa.Column('fmw_orderby', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fmw_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('fmw_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('fmw_id', 'fmw_dbtype', 'fmw_crud')
    )
    op.create_table('ly_query',
    sa.Column('query_id', sa.INTEGER(), nullable=False),
    sa.Column('query_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('query_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('query_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('query_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_table('ly_roles',
    sa.Column('rol_id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('rol_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('rol_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('rol_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('rol_id')
    )
    op.create_table('ly_sequence',
    sa.Column('seq_id', sa.INTEGER(), nullable=False),
    sa.Column('seq_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('seq_query_id', sa.INTEGER(), nullable=True),
    sa.Column('seq_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('seq_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('seq_dd_id', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('seq_id')
    )
    op.create_table('ly_tables',
    sa.Column('tbl_id', sa.INTEGER(), nullable=False),
    sa.Column('tbl_db_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tbl_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tbl_query_id', sa.INTEGER(), nullable=True),
    sa.Column('tbl_editable', sa.VARCHAR(length=1), nullable=True),
    sa.Column('tbl_uploadable', sa.VARCHAR(length=1), nullable=True),
    sa.Column('tbl_audit', sa.VARCHAR(length=1), nullable=True),
    sa.Column('tbl_burst', sa.VARCHAR(length=1), nullable=True),
    sa.Column('tbl_workbook', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tbl_sheet', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tbl_ctx_id', sa.INTEGER(), nullable=True),
    sa.Column('tbl_tree_id', sa.INTEGER(), nullable=True),
    sa.Column('tbl_frm_id', sa.INTEGER(), nullable=True),
    sa.Column('tbl_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tbl_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('tbl_auto_load', sa.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('tbl_id')
    )
    op.create_table('ly_themes',
    sa.Column('thm_id', sa.INTEGER(), nullable=False),
    sa.Column('thm_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('thm_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('thm_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('thm_id')
    )
    op.create_table('ly_tree',
    sa.Column('tree_id', sa.INTEGER(), nullable=False),
    sa.Column('tree_description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tree_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('tree_parent', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tree_child', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tree_key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tree_group', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tree_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tree_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tree_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('tree_id')
    )
    op.create_table('ly_users',
    sa.Column('usr_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('usr_password', sa.TEXT(), nullable=True),
    sa.Column('usr_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('usr_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('usr_status', sa.VARCHAR(length=1), nullable=True),
    sa.Column('usr_admin', sa.VARCHAR(length=1), nullable=True),
    sa.Column('usr_language', sa.VARCHAR(length=3), nullable=True),
    sa.Column('usr_mode', sa.VARCHAR(length=10), nullable=True),
    sa.Column('usr_readonly', sa.VARCHAR(length=1), nullable=True),
    sa.Column('usr_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('usr_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('usr_dashboard', sa.INTEGER(), nullable=True),
    sa.Column('usr_theme', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('usr_id')
    )
    op.create_table('ly_act_branch',
    sa.Column('act_id', sa.INTEGER(), nullable=False),
    sa.Column('brc_id', sa.INTEGER(), nullable=False),
    sa.Column('brc_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('brc_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('brc_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['ly_actions.act_id'], ),
    sa.PrimaryKeyConstraint('act_id', 'brc_id')
    )
    op.create_table('ly_act_params',
    sa.Column('act_id', sa.INTEGER(), nullable=False),
    sa.Column('map_var', sa.VARCHAR(length=50), nullable=False),
    sa.Column('map_dir', sa.VARCHAR(length=20), nullable=True),
    sa.Column('map_display', sa.VARCHAR(length=1), nullable=True),
    sa.Column('map_rules', sa.VARCHAR(length=10), nullable=True),
    sa.Column('map_rules_values', sa.VARCHAR(length=50), nullable=True),
    sa.Column('map_default', sa.VARCHAR(length=100), nullable=True),
    sa.Column('map_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('map_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['ly_actions.act_id'], ),
    sa.PrimaryKeyConstraint('act_id', 'map_var')
    )
    op.create_table('ly_act_tasks',
    sa.Column('act_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_seq', sa.INTEGER(), nullable=False),
    sa.Column('evt_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('evt_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('evt_disabled', sa.VARCHAR(length=1), nullable=True),
    sa.Column('evt_query_id', sa.INTEGER(), nullable=True),
    sa.Column('evt_query_crud', sa.VARCHAR(length=10), nullable=True),
    sa.Column('evt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('evt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('evt_cdn_id', sa.INTEGER(), nullable=True),
    sa.Column('evt_brc_true', sa.INTEGER(), nullable=True),
    sa.Column('evt_brc_false', sa.INTEGER(), nullable=True),
    sa.Column('evt_brc_id', sa.INTEGER(), nullable=True),
    sa.Column('evt_api_id', sa.INTEGER(), nullable=True),
    sa.Column('evt_component', sa.VARCHAR(length=20), nullable=True),
    sa.Column('evt_component_id', sa.INTEGER(), nullable=True),
    sa.Column('evt_loop', sa.VARCHAR(length=1), nullable=True),
    sa.Column('evt_loop_array', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['ly_actions.act_id'], ),
    sa.PrimaryKeyConstraint('act_id', 'evt_id')
    )
    op.create_table('ly_cdn_grp',
    sa.Column('cdn_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_group', sa.INTEGER(), nullable=False),
    sa.Column('cdn_label', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cdn_logical', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cdn_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cdn_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['cdn_id'], ['ly_condition.cdn_id'], ),
    sa.PrimaryKeyConstraint('cdn_id', 'cdn_group')
    )
    op.create_table('ly_cdn_params',
    sa.Column('cdn_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_params_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_seq', sa.INTEGER(), nullable=False),
    sa.Column('cdn_dd_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cdn_operator', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cdn_value', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cdn_enum_id', sa.INTEGER(), nullable=True),
    sa.Column('cdn_lookup_id', sa.INTEGER(), nullable=True),
    sa.Column('cdn_logical', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cdn_group', sa.INTEGER(), nullable=True),
    sa.Column('cdn_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cdn_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('cdn_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cdn_grp_label', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cdn_id'], ['ly_condition.cdn_id'], ),
    sa.PrimaryKeyConstraint('cdn_id', 'cdn_params_id')
    )
    op.create_table('ly_ctx_val',
    sa.Column('ctx_id', sa.INTEGER(), nullable=False),
    sa.Column('val_id', sa.INTEGER(), nullable=False),
    sa.Column('val_seq', sa.INTEGER(), nullable=True),
    sa.Column('val_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('val_component', sa.VARCHAR(length=40), nullable=True),
    sa.Column('val_component_id', sa.INTEGER(), nullable=True),
    sa.Column('val_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('val_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ctx_id'], ['ly_ctxmenus.ctx_id'], ),
    sa.PrimaryKeyConstraint('ctx_id', 'val_id')
    )
    op.create_table('ly_dictionary_filters',
    sa.Column('dd_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('flt_id', sa.INTEGER(), nullable=False),
    sa.Column('flt_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('flt_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('flt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('flt_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dd_id'], ['ly_dictionary.dd_id'], ),
    sa.PrimaryKeyConstraint('dd_id', 'flt_id')
    )
    op.create_table('ly_dictionary_l',
    sa.Column('dd_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('lng_id', sa.VARCHAR(length=4), nullable=False),
    sa.Column('lng_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lng_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lng_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['dd_id'], ['ly_dictionary.dd_id'], ),
    sa.PrimaryKeyConstraint('dd_id', 'lng_id')
    )
    op.create_table('ly_dlg_frm',
    sa.Column('dlg_id', sa.INTEGER(), nullable=False),
    sa.Column('frm_id', sa.INTEGER(), nullable=False),
    sa.Column('frm_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('frm_query_id', sa.INTEGER(), nullable=True),
    sa.Column('frm_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('frm_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['dlg_id'], ['ly_dialogs.dlg_id'], ),
    sa.PrimaryKeyConstraint('frm_id')
    )
    op.create_table('ly_dsh_col',
    sa.Column('dsh_id', sa.INTEGER(), nullable=False),
    sa.Column('dsh_col_id', sa.INTEGER(), nullable=False),
    sa.Column('dsh_display_title', sa.VARCHAR(length=1), nullable=True),
    sa.Column('dsh_title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dsh_row', sa.INTEGER(), nullable=True),
    sa.Column('dsh_column', sa.INTEGER(), nullable=True),
    sa.Column('dsh_component', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dsh_component_id', sa.INTEGER(), nullable=True),
    sa.Column('dsh_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('dsh_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['dsh_id'], ['ly_dashboard.dsh_id'], ),
    sa.PrimaryKeyConstraint('dsh_id', 'dsh_col_id')
    )
    op.create_table('ly_enum_val',
    sa.Column('enum_id', sa.INTEGER(), nullable=False),
    sa.Column('val_enum', sa.VARCHAR(length=20), nullable=False),
    sa.Column('val_label', sa.VARCHAR(length=200), nullable=True),
    sa.Column('val_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('val_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['enum_id'], ['ly_enum.enum_id'], ),
    sa.PrimaryKeyConstraint('enum_id', 'val_enum')
    )
    op.create_table('ly_lkp_params',
    sa.Column('lkp_id', sa.INTEGER(), nullable=False),
    sa.Column('dd_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('lkp_dir', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['lkp_id'], ['ly_lookup.lkp_id'], ),
    sa.PrimaryKeyConstraint('lkp_id', 'dd_id')
    )
    op.create_table('ly_lnk_val',
    sa.Column('lnk_id', sa.INTEGER(), nullable=False),
    sa.Column('val_id', sa.INTEGER(), nullable=False),
    sa.Column('val_sequence', sa.INTEGER(), nullable=False),
    sa.Column('val_label', sa.VARCHAR(length=40), nullable=True),
    sa.Column('val_link', sa.VARCHAR(length=250), nullable=True),
    sa.Column('val_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('val_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['lnk_id'], ['ly_links.lnk_id'], ),
    sa.PrimaryKeyConstraint('lnk_id', 'val_id')
    )
    op.create_table('ly_menus_filters',
    sa.Column('menu_seq_ukid', sa.VARCHAR(length=150), nullable=False),
    sa.Column('flt_id', sa.INTEGER(), nullable=False),
    sa.Column('flt_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('flt_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('flt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('flt_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['menu_seq_ukid'], ['ly_menus.menu_seq_ukid'], ),
    sa.PrimaryKeyConstraint('menu_seq_ukid', 'flt_id')
    )
    op.create_table('ly_menus_l',
    sa.Column('lng_id', sa.VARCHAR(length=4), nullable=False),
    sa.Column('lng_seq_ukid', sa.VARCHAR(length=150), nullable=False),
    sa.Column('lng_label', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lng_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lng_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['lng_seq_ukid'], ['ly_menus.menu_seq_ukid'], ),
    sa.PrimaryKeyConstraint('lng_id', 'lng_seq_ukid')
    )
    op.create_table('ly_qry_sql',
    sa.Column('query_id', sa.INTEGER(), nullable=False),
    sa.Column('query_dbtype', sa.VARCHAR(length=10), nullable=False),
    sa.Column('query_crud', sa.VARCHAR(length=10), nullable=False),
    sa.Column('query_pool', sa.VARCHAR(length=10), nullable=False),
    sa.Column('query_sqlquery', sa.TEXT(), nullable=True),
    sa.Column('query_orderby', sa.VARCHAR(length=100), nullable=True),
    sa.Column('query_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('query_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['ly_query.query_id'], ),
    sa.PrimaryKeyConstraint('query_id', 'query_dbtype', 'query_crud')
    )
    op.create_table('ly_rol_auth',
    sa.Column('rol_id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('aut_id', sa.INTEGER(), nullable=False),
    sa.Column('aut_component', sa.VARCHAR(length=40), nullable=True),
    sa.Column('aut_component_id', sa.INTEGER(), nullable=True),
    sa.Column('aut_dd_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('aut_menu_seq_ukid', sa.VARCHAR(length=150), nullable=True),
    sa.Column('aut_run', sa.VARCHAR(length=1), nullable=True),
    sa.Column('aut_add', sa.VARCHAR(length=1), nullable=True),
    sa.Column('aut_chg', sa.VARCHAR(length=1), nullable=True),
    sa.Column('aut_del', sa.VARCHAR(length=1), nullable=True),
    sa.Column('aut_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('aut_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['ly_roles.rol_id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'aut_id')
    )
    op.create_table('ly_seq_params',
    sa.Column('seq_id', sa.INTEGER(), nullable=False),
    sa.Column('dd_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['seq_id'], ['ly_sequence.seq_id'], ),
    sa.PrimaryKeyConstraint('seq_id', 'dd_id')
    )
    op.create_table('ly_tbl_col',
    sa.Column('tbl_id', sa.INTEGER(), nullable=False),
    sa.Column('col_id', sa.INTEGER(), nullable=False),
    sa.Column('col_seq', sa.INTEGER(), nullable=True),
    sa.Column('col_dd_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('col_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('col_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('col_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('col_rules', sa.VARCHAR(length=20), nullable=True),
    sa.Column('col_rules_values', sa.VARCHAR(length=50), nullable=True),
    sa.Column('col_default', sa.VARCHAR(length=50), nullable=True),
    sa.Column('col_visible', sa.VARCHAR(length=1), nullable=True),
    sa.Column('col_disabled', sa.VARCHAR(length=1), nullable=True),
    sa.Column('col_required', sa.VARCHAR(length=1), nullable=True),
    sa.Column('col_key', sa.VARCHAR(length=1), nullable=True),
    sa.Column('col_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('col_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('col_filter', sa.VARCHAR(length=1), nullable=True),
    sa.Column('col_cdn_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tbl_id'], ['ly_tables.tbl_id'], ),
    sa.PrimaryKeyConstraint('tbl_id', 'col_id')
    )
    op.create_table('ly_thm_colors',
    sa.Column('thm_id', sa.INTEGER(), nullable=False),
    sa.Column('tcl_id', sa.INTEGER(), nullable=False),
    sa.Column('tcl_key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('tcl_light', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tcl_dark', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tcl_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tcl_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['thm_id'], ['ly_themes.thm_id'], ),
    sa.PrimaryKeyConstraint('thm_id', 'tcl_id')
    )
    op.create_table('ly_usr_roles',
    sa.Column('usr_id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('rol_id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('rlu_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('rlu_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['ly_roles.rol_id'], ),
    sa.ForeignKeyConstraint(['usr_id'], ['ly_users.usr_id'], ),
    sa.PrimaryKeyConstraint('usr_id', 'rol_id')
    )
    op.create_table('ly_act_params_filters',
    sa.Column('act_id', sa.INTEGER(), nullable=False),
    sa.Column('map_var', sa.VARCHAR(length=50), nullable=False),
    sa.Column('flt_id', sa.INTEGER(), nullable=False),
    sa.Column('flt_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('flt_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_value', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('flt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['act_id', 'map_var'], ['ly_act_params.act_id', 'ly_act_params.map_var'], ),
    sa.PrimaryKeyConstraint('act_id', 'map_var', 'flt_id')
    )
    op.create_table('ly_act_tasks_params',
    sa.Column('act_id', sa.INTEGER(), nullable=False),
    sa.Column('evt_id', sa.INTEGER(), nullable=False),
    sa.Column('map_id', sa.INTEGER(), nullable=False),
    sa.Column('map_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('map_dir', sa.VARCHAR(length=20), nullable=True),
    sa.Column('map_var', sa.VARCHAR(length=50), nullable=True),
    sa.Column('map_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('map_var_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('map_value', sa.VARCHAR(length=50), nullable=True),
    sa.Column('map_rules', sa.VARCHAR(length=20), nullable=True),
    sa.Column('map_rules_values', sa.VARCHAR(length=50), nullable=True),
    sa.Column('map_default', sa.VARCHAR(length=100), nullable=True),
    sa.Column('map_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('map_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['act_id', 'evt_id'], ['ly_act_tasks.act_id', 'ly_act_tasks.evt_id'], ),
    sa.PrimaryKeyConstraint('act_id', 'evt_id', 'map_id')
    )
    op.create_table('ly_ctx_filters',
    sa.Column('ctx_id', sa.INTEGER(), nullable=False),
    sa.Column('val_id', sa.INTEGER(), nullable=False),
    sa.Column('flt_id', sa.INTEGER(), nullable=False),
    sa.Column('flt_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('flt_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('flt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('flt_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ctx_id', 'val_id'], ['ly_ctx_val.ctx_id', 'ly_ctx_val.val_id'], ),
    sa.PrimaryKeyConstraint('ctx_id', 'val_id', 'flt_id')
    )
    op.create_table('ly_ctx_val_l',
    sa.Column('ctx_id', sa.INTEGER(), nullable=False),
    sa.Column('val_id', sa.INTEGER(), nullable=False),
    sa.Column('lng_id', sa.VARCHAR(length=4), nullable=False),
    sa.Column('lng_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lng_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lng_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ctx_id', 'val_id'], ['ly_ctx_val.ctx_id', 'ly_ctx_val.val_id'], ),
    sa.PrimaryKeyConstraint('ctx_id', 'val_id', 'lng_id')
    )
    op.create_table('ly_dlg_col',
    sa.Column('frm_id', sa.INTEGER(), nullable=False),
    sa.Column('col_id', sa.INTEGER(), nullable=False),
    sa.Column('tab_id', sa.INTEGER(), nullable=False),
    sa.Column('col_seq', sa.INTEGER(), nullable=True),
    sa.Column('col_colspan', sa.INTEGER(), nullable=True),
    sa.Column('col_component', sa.VARCHAR(length=20), nullable=False),
    sa.Column('col_component_id', sa.INTEGER(), nullable=True),
    sa.Column('col_dd_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('col_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('col_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('col_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('col_rules', sa.VARCHAR(length=20), nullable=True),
    sa.Column('col_rules_values', sa.VARCHAR(length=50), nullable=True),
    sa.Column('col_default', sa.VARCHAR(length=50), nullable=True),
    sa.Column('col_visible', sa.VARCHAR(length=1), nullable=True),
    sa.Column('col_disabled', sa.VARCHAR(length=1), nullable=True),
    sa.Column('col_required', sa.VARCHAR(length=1), nullable=True),
    sa.Column('col_key', sa.VARCHAR(length=1), nullable=True),
    sa.Column('col_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('col_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('col_cdn_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['frm_id'], ['ly_dlg_frm.frm_id'], ),
    sa.PrimaryKeyConstraint('frm_id', 'col_id')
    )
    op.create_table('ly_dlg_tab',
    sa.Column('frm_id', sa.INTEGER(), nullable=False),
    sa.Column('tab_id', sa.INTEGER(), nullable=False),
    sa.Column('tab_seq', sa.INTEGER(), nullable=True),
    sa.Column('tab_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tab_cdn_id', sa.INTEGER(), nullable=True),
    sa.Column('tab_cols', sa.INTEGER(), nullable=True),
    sa.Column('tab_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tab_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('tab_disable_add', sa.VARCHAR(length=1), nullable=True),
    sa.Column('tab_disable_edit', sa.VARCHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['frm_id'], ['ly_dlg_frm.frm_id'], ),
    sa.PrimaryKeyConstraint('frm_id', 'tab_id')
    )
    op.create_table('ly_enum_val_l',
    sa.Column('enum_id', sa.INTEGER(), nullable=False),
    sa.Column('val_enum', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lng_id', sa.VARCHAR(length=4), nullable=False),
    sa.Column('lng_label', sa.VARCHAR(length=200), nullable=True),
    sa.Column('lng_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lng_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['enum_id', 'val_enum'], ['ly_enum_val.enum_id', 'ly_enum_val.val_enum'], ),
    sa.PrimaryKeyConstraint('enum_id', 'val_enum', 'lng_id')
    )
    op.create_table('ly_lnk_val_l',
    sa.Column('lnk_id', sa.INTEGER(), nullable=False),
    sa.Column('val_id', sa.INTEGER(), nullable=False),
    sa.Column('lng_id', sa.VARCHAR(length=4), nullable=False),
    sa.Column('lng_label', sa.VARCHAR(length=40), nullable=True),
    sa.Column('lng_link', sa.VARCHAR(length=250), nullable=True),
    sa.Column('lng_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lng_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['lnk_id', 'val_id'], ['ly_lnk_val.lnk_id', 'ly_lnk_val.val_id'], ),
    sa.PrimaryKeyConstraint('lnk_id', 'val_id', 'lng_id')
    )
    op.create_table('ly_tbl_col_cdn',
    sa.Column('tbl_id', sa.INTEGER(), nullable=False),
    sa.Column('col_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('cdn_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cdn_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cdn_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cdn_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('cdn_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tbl_id', 'col_id'], ['ly_tbl_col.tbl_id', 'ly_tbl_col.col_id'], ),
    sa.PrimaryKeyConstraint('tbl_id', 'col_id', 'cdn_id')
    )
    op.create_table('ly_tbl_filters',
    sa.Column('tbl_id', sa.INTEGER(), nullable=False),
    sa.Column('col_id', sa.INTEGER(), nullable=False),
    sa.Column('flt_id', sa.INTEGER(), nullable=False),
    sa.Column('flt_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('flt_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('flt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('flt_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tbl_id', 'col_id'], ['ly_tbl_col.tbl_id', 'ly_tbl_col.col_id'], ),
    sa.PrimaryKeyConstraint('tbl_id', 'col_id', 'flt_id')
    )
    op.create_table('ly_dlg_col_cdn',
    sa.Column('frm_id', sa.INTEGER(), nullable=False),
    sa.Column('col_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('cdn_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cdn_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cdn_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cdn_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('cdn_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['frm_id', 'col_id'], ['ly_dlg_col.frm_id', 'ly_dlg_col.col_id'], ),
    sa.PrimaryKeyConstraint('frm_id', 'col_id', 'cdn_id')
    )
    op.create_table('ly_dlg_filters',
    sa.Column('frm_id', sa.INTEGER(), nullable=False),
    sa.Column('col_id', sa.INTEGER(), nullable=False),
    sa.Column('flt_id', sa.INTEGER(), nullable=False),
    sa.Column('flt_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('flt_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flt_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('flt_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('flt_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['frm_id', 'col_id'], ['ly_dlg_col.frm_id', 'ly_dlg_col.col_id'], ),
    sa.PrimaryKeyConstraint('frm_id', 'col_id', 'flt_id')
    )
    op.create_table('ly_dlg_tab_cdn',
    sa.Column('frm_id', sa.INTEGER(), nullable=False),
    sa.Column('tab_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_id', sa.INTEGER(), nullable=False),
    sa.Column('cdn_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('cdn_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cdn_target', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cdn_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cdn_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('cdn_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['frm_id'], ['ly_dlg_frm.frm_id'], ),
    sa.ForeignKeyConstraint(['tab_id'], ['ly_dlg_tab.tab_id'], ),
    sa.PrimaryKeyConstraint('frm_id', 'tab_id', 'cdn_id')
    )
    op.create_table('ly_dlg_tab_l',
    sa.Column('frm_id', sa.INTEGER(), nullable=False),
    sa.Column('tab_id', sa.INTEGER(), nullable=False),
    sa.Column('lng_id', sa.VARCHAR(length=4), nullable=False),
    sa.Column('lng_label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lng_audit_user', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lng_audit_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['frm_id', 'tab_id'], ['ly_dlg_tab.frm_id', 'ly_dlg_tab.tab_id'], ),
    sa.PrimaryKeyConstraint('frm_id', 'tab_id', 'lng_id')
    )
    # ### end Alembic commands ###


def downgrade_liberty() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ly_dlg_tab_l')
    op.drop_table('ly_dlg_tab_cdn')
    op.drop_table('ly_dlg_filters')
    op.drop_table('ly_dlg_col_cdn')
    op.drop_table('ly_tbl_filters')
    op.drop_table('ly_tbl_col_cdn')
    op.drop_table('ly_lnk_val_l')
    op.drop_table('ly_enum_val_l')
    op.drop_table('ly_dlg_tab')
    op.drop_table('ly_dlg_col')
    op.drop_table('ly_ctx_val_l')
    op.drop_table('ly_ctx_filters')
    op.drop_table('ly_act_tasks_params')
    op.drop_table('ly_act_params_filters')
    op.drop_table('ly_usr_roles')
    op.drop_table('ly_thm_colors')
    op.drop_table('ly_tbl_col')
    op.drop_table('ly_seq_params')
    op.drop_table('ly_rol_auth')
    op.drop_table('ly_qry_sql')
    op.drop_table('ly_menus_l')
    op.drop_table('ly_menus_filters')
    op.drop_table('ly_lnk_val')
    op.drop_table('ly_lkp_params')
    op.drop_table('ly_enum_val')
    op.drop_table('ly_dsh_col')
    op.drop_table('ly_dlg_frm')
    op.drop_table('ly_dictionary_l')
    op.drop_table('ly_dictionary_filters')
    op.drop_table('ly_ctx_val')
    op.drop_table('ly_cdn_params')
    op.drop_table('ly_cdn_grp')
    op.drop_table('ly_act_tasks')
    op.drop_table('ly_act_params')
    op.drop_table('ly_act_branch')
    op.drop_table('ly_users')
    op.drop_table('ly_tree')
    op.drop_table('ly_themes')
    op.drop_table('ly_tables')
    op.drop_table('ly_sequence')
    op.drop_table('ly_roles')
    op.drop_table('ly_query')
    op.drop_table('ly_qry_fmw')
    op.drop_table('ly_nextnum')
    op.drop_table('ly_modules')
    op.drop_table('ly_menus')
    op.drop_table('ly_lookup')
    op.drop_table('ly_links')
    op.drop_table('ly_language')
    op.drop_table('ly_function')
    op.drop_table('ly_evt_dd')
    op.drop_table('ly_evt_cpt')
    op.drop_table('ly_events')
    op.drop_table('ly_enum')
    op.drop_table('ly_dictionary')
    op.drop_table('ly_dialogs')
    op.drop_table('ly_db_schema')
    op.drop_table('ly_dashboard')
    op.drop_table('ly_ctxmenus')
    op.drop_table('ly_condition')
    op.drop_table('ly_components')
    op.drop_table('ly_charts')
    op.drop_table('ly_applications')
    op.drop_table('ly_api_params')
    op.drop_table('ly_api_header')
    op.drop_table('ly_api')
    op.drop_table('ly_actions')
    op.drop_table('databasechangeloglock')
    # ### end Alembic commands ###

