"""Initial schema

Revision ID: 766e5a82b42f
Revises: 
Create Date: 2025-02-02 00:20:19.117366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '766e5a82b42f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_liberty() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databasechangelog')
    # ### end Alembic commands ###


def downgrade_liberty() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databasechangelog',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dateexecuted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('orderexecuted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exectype', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('md5sum', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('liquibase', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contexts', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('labels', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('deployment_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###


def upgrade_libnsx1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databasechangelog')
    op.drop_constraint('lydlgtabcdn_fk1', 'ly_dlg_tab_cdn', type_='foreignkey')
    op.drop_constraint('lytblcolcdn_fk1', 'ly_tbl_col_cdn', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade_libnsx1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('lytblcolcdn_fk1', 'ly_tbl_col_cdn', 'ly_tables', ['tbl_id'], ['tbl_id'], ondelete='CASCADE')
    op.create_foreign_key('lydlgtabcdn_fk1', 'ly_dlg_tab_cdn', 'ly_dlg_frm', ['frm_id'], ['frm_id'], ondelete='CASCADE')
    op.create_table('databasechangelog',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dateexecuted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('orderexecuted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exectype', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('md5sum', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('liquibase', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contexts', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('labels', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('deployment_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###


def upgrade_libnjde() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databasechangelog')
    op.drop_constraint('lytblcolcdn_fk1', 'ly_tbl_col_cdn', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade_libnjde() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('lytblcolcdn_fk1', 'ly_tbl_col_cdn', 'ly_tables', ['tbl_id'], ['tbl_id'], ondelete='CASCADE')
    op.create_table('databasechangelog',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dateexecuted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('orderexecuted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exectype', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('md5sum', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('liquibase', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contexts', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('labels', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('deployment_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###


def upgrade_libnetl() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databasechangelog')
    op.drop_constraint('lydlgtabcdn_fk1', 'ly_dlg_tab_cdn', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade_libnetl() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('lydlgtabcdn_fk1', 'ly_dlg_tab_cdn', 'ly_dlg_frm', ['frm_id'], ['frm_id'], ondelete='CASCADE')
    op.create_table('databasechangelog',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dateexecuted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('orderexecuted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exectype', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('md5sum', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('liquibase', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contexts', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('labels', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('deployment_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###


def upgrade_nomasx1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databasechangelog')
    op.drop_table('aud$_sod_process')
    op.drop_table('aud$_license_csi')
    # ### end Alembic commands ###


def downgrade_nomasx1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aud$_license_csi',
    sa.Column('csi_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('csi_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('csi_from_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('csi_to_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('csi_status', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('csi_audit_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('csi_audit_date', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('aud$_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('aud$_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('aud$_sod_process',
    sa.Column('process_apps_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('process_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('process_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('process_audit_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('process_audit_date', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('process_ukid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aud$_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('aud$_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('databasechangelog',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dateexecuted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('orderexecuted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exectype', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('md5sum', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('liquibase', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contexts', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('labels', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('deployment_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###

