services:
  fastapi:
    build:
      platforms: 
        - linux/arm64      
      context: ../../.
      dockerfile: ./docker/framework/Dockerfile
    image: ghcr.io/fblettner/liberty-framework:latest
    #command: ["fastapi", "run", "main.py"]
    command: [liberty-start]
    security_opt:
      - "label:disable"
    cap_drop:
      - MKNOD
      - AUDIT_WRITE
    networks:
      - liberty-network
    working_dir: /
    ports:
      - 8000:8000
networks:
  liberty-network:
    name: liberty-network
    external: true